---
title: "Simulation-and-Analysis-Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Simulation and Data Analysis Project
Nicole Scott

##*Simulation*

##Overview

##Simulation

```{r simulation}
lambda <- 0.2
sample <- rexp(40*1000, rate = lambda)
samplemat <- matrix(sample, nrow = 1000, ncol = 40)

```

```{r simulation plot, fig.width= 8}
library(ggplot2)
ggplot() +
        geom_density(aes(sample), color = "grey", fill = "steelblue")
```

##Sample Mean versus Theoretical Mean

```{r means}
samplemeans <- rowMeans(samplemat)
ggplot()+
        geom_histogram(aes(samplemeans), color = "grey", fill = "steelblue", 
                       bins = 10) +
        geom_vline(xintercept = mean(samplemeans))
samplemean <- mean(samplemeans)
theorymean <- 1/lambda
```

##Sample Variance versus Theoretical Variance

```{r variance}
samplesd <- apply(samplemat, 1, sd)
ggplot()+
        geom_histogram(aes(samplesd), color = "grey", fill = "steelblue", 
                       bins = 10)+
        geom_vline(xintercept = mean(samplesd))
meansd <- mean(samplesd)
theorysd <- 1/lambda
```

##Distribution

===============================================================================

##*Tooth Growth Data Analysis*

##Exploratory Analysis

##Data Summary

##Analysis

##Conclusions